## Checking the original file's cleanliness

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('C:/Users/Syahirahar/Documents/GitHub/MyDataEngineeringProject/Invistico_Airline.csv')
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,id,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Timestamp,Code,Location
0,212-12-2276,satisfied,Female,Loyal Customer,65.0,Personal Travel,Eco,265.0,0.0,0.0,0.0,2.0,2.0,4.0,2.0,3.0,3.0,0.0,3.0,5.0,3.0,2.0,0.0,0.0,12/4/2021 9:08,DE,Europe/Berlin)
1,304-60-7707,satisfied,Male,Loyal Customer,47.0,Personal Travel,Business,2464.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,3.0,4.0,4.0,4.0,2.0,3.0,2.0,310.0,305.0,19/4/2021 12:48,RE,Indian/Reunion)
2,832-31-5861,satisfied,Female,Loyal Customer,15.0,Personal Travel,Eco,2138.0,0.0,0.0,0.0,3.0,2.0,0.0,2.0,2.0,3.0,3.0,4.0,4.0,4.0,2.0,0.0,0.0,1/5/2021 8:05,UA,Europe/Kiev)
3,650-80-4379,satisfied,Female,Loyal Customer,60.0,Personal Travel,Eco,623.0,0.0,0.0,0.0,3.0,3.0,4.0,3.0,1.0,1.0,0.0,1.0,4.0,1.0,3.0,0.0,0.0,3/5/2021 9:33,US,America/New_York)
4,721-02-2779,satisfied,Female,Loyal Customer,70.0,Personal Travel,Eco,354.0,0.0,0.0,0.0,3.0,4.0,3.0,4.0,2.0,2.0,0.0,2.0,4.0,2.0,5.0,0.0,0.0,25/4/2021 21:29,ES,Europe/Madrid)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129881 entries, 0 to 129880
Data columns (total 27 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 129881 non-null  object
 1   satisfaction                       129880 non-null  object
 2   Gender                             129880 non-null  object
 3   Customer Type                      129880 non-null  object
 4   Age                                129880 non-null  float64
 5   Type of Travel                     129880 non-null  object
 6   Class                              129880 non-null  object
 7   Flight Distance                    129880 non-null  float64
 8   Seat comfort                       129880 non-null  float64
 9   Departure/Arrival time convenient  129880 non-null  float64
 10  Food and drink                     129880 non-null  float64
 11  Gate location                      129880 non-null  float64
 12  Inflight wifi service              129880 non-null  float64
 13  Inflight entertainment             129880 non-null  float64
 14  Online support                     129880 non-null  float64
 15  Ease of Online booking             129880 non-null  float64
 16  On-board service                   129880 non-null  float64
 17  Leg room service                   129880 non-null  float64
 18  Baggage handling                   129880 non-null  float64
 19  Checkin service                    129880 non-null  float64
 20  Cleanliness                        129880 non-null  float64
 21  Online boarding                    129880 non-null  float64
 22  Departure Delay in Minutes         129880 non-null  float64
 23  Arrival Delay in Minutes           129487 non-null  float64
 24  Timestamp                          129881 non-null  object
 25  Code                               129881 non-null  object
 26  Location                           129881 non-null  object
dtypes: float64(18), object(9)
memory usage: 26.8+ MB

In [7]:
(df.duplicated().value_counts()/df.shape[0])*100

False    100.0
dtype: float64

## Merge ori and fake_generated_data

In [8]:
airline_data = df

In [9]:
fake_data = pd.read_csv('C:/Users/Syahirahar/Documents/GitHub/MyDataEngineeringProject/generate_fake_data.csv')

In [10]:
result = pd.concat([airline_data,fake_data], axis=1)

In [11]:
result.head()

,id,satisfaction,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Timestamp,Code,Location,Unnamed: 0,flight_id,review_id,timestamp,Names,Gender,Destination
0,212-12-2276,satisfied,Female,Loyal Customer,65.0,Personal Travel,Eco,265.0,0.0,0.0,0.0,2.0,2.0,4.0,2.0,3.0,3.0,0.0,3.0,5.0,3.0,2.0,0.0,0.0,12/4/2021 9:08,DE,Europe/Berlin),0.0,141-44-9212,2.0,1970-01-01 04:46:17,Cristen Rohan,F,Los_Angeles
1,304-60-7707,satisfied,Male,Loyal Customer,47.0,Personal Travel,Business,2464.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,3.0,4.0,4.0,4.0,2.0,3.0,2.0,310.0,305.0,19/4/2021 12:48,RE,Indian/Reunion),1.0,379-86-9265,1.0,1970-01-01 04:50:21,Parlee McKenzie,F,Los_Angeles
2,832-31-5861,satisfied,Female,Loyal Customer,15.0,Personal Travel,Eco,2138.0,0.0,0.0,0.0,3.0,2.0,0.0,2.0,2.0,3.0,3.0,4.0,4.0,4.0,2.0,0.0,0.0,1/5/2021 8:05,UA,Europe/Kiev),2.0,295-92-4148,8.0,1970-01-01 04:48:34,Jaron Wyman,M,Los_Angeles
3,650-80-4379,satisfied,Female,Loyal Customer,60.0,Personal Travel,Eco,623.0,0.0,0.0,0.0,3.0,3.0,4.0,3.0,1.0,1.0,0.0,1.0,4.0,1.0,3.0,0.0,0.0,3/5/2021 9:33,US,America/New_York),3.0,897-61-5856,3.0,1970-01-01 04:51:03,Jody Rau,M,Los_Angeles
4,721-02-2779,satisfied,Female,Loyal Customer,70.0,Personal Travel,Eco,354.0,0.0,0.0,0.0,3.0,4.0,3.0,4.0,2.0,2.0,0.0,2.0,4.0,2.0,5.0,0.0,0.0,25/4/2021 21:29,ES,Europe/Madrid),4.0,120-70-3397,8.0,1970-01-01 04:51:19,Taliyah Smitham,F,Los_Angeles

In [13]:
result.columns

Index(['id', 'satisfaction', 'Gender', 'Customer Type', 'Age',
       'Type of Travel', 'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Timestamp',
       'Code', 'Location', 'Unnamed: 0', 'flight_id', 'review_id', 'timestamp',
       'Names', 'Gender', 'Destination'],
      dtype='object')

In [14]:
final_result = result[['review_id','flight_id','timestamp','Names', 'Gender','Customer Type', 'Age',
       'Type of Travel', 'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Timestamp',
       'Code', 'Location']]

In [15]:
final_result.head()

,review_id,flight_id,timestamp,Names,Gender,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes,Timestamp,Code,Location
0,2.0,141-44-9212,1970-01-01 04:46:17,Cristen Rohan,Female,F,Loyal Customer,65.0,Personal Travel,Eco,265.0,0.0,0.0,0.0,2.0,2.0,4.0,2.0,3.0,3.0,0.0,3.0,5.0,3.0,2.0,0.0,0.0,12/4/2021 9:08,DE,Europe/Berlin)
1,1.0,379-86-9265,1970-01-01 04:50:21,Parlee McKenzie,Male,F,Loyal Customer,47.0,Personal Travel,Business,2464.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,3.0,4.0,4.0,4.0,2.0,3.0,2.0,310.0,305.0,19/4/2021 12:48,RE,Indian/Reunion)
2,8.0,295-92-4148,1970-01-01 04:48:34,Jaron Wyman,Female,M,Loyal Customer,15.0,Personal Travel,Eco,2138.0,0.0,0.0,0.0,3.0,2.0,0.0,2.0,2.0,3.0,3.0,4.0,4.0,4.0,2.0,0.0,0.0,1/5/2021 8:05,UA,Europe/Kiev)
3,3.0,897-61-5856,1970-01-01 04:51:03,Jody Rau,Female,M,Loyal Customer,60.0,Personal Travel,Eco,623.0,0.0,0.0,0.0,3.0,3.0,4.0,3.0,1.0,1.0,0.0,1.0,4.0,1.0,3.0,0.0,0.0,3/5/2021 9:33,US,America/New_York)
4,8.0,120-70-3397,1970-01-01 04:51:19,Taliyah Smitham,Female,F,Loyal Customer,70.0,Personal Travel,Eco,354.0,0.0,0.0,0.0,3.0,4.0,3.0,4.0,2.0,2.0,0.0,2.0,4.0,2.0,5.0,0.0,0.0,25/4/2021 21:29,ES,Europe/Madrid)

In [18]:
final_result.dtypes

review_id                            float64
flight_id                             object
timestamp                             object
Names                                 object
Gender                                object
Gender                                object
Customer Type                         object
Age                                  float64
Type of Travel                        object
Class                                 object
Flight Distance                      float64
Seat comfort                         float64
Departure/Arrival time convenient    float64
Food and drink                       float64
Gate location                        float64
Inflight wifi service                float64
Inflight entertainment               float64
Online support                       float64
Ease of Online booking               float64
On-board service                     float64
Leg room service                     float64
Baggage handling                     float64
Checkin service                      float64
Cleanliness                          float64
Online boarding                      float64
Departure Delay in Minutes           float64
Arrival Delay in Minutes             float64
Timestamp                             object
Code                                  object
Location                              object
dtype: object